CREATE TABLE batman(
   id     INTEGER  NOT NULL PRIMARY KEY 
  ,quote  VARCHAR(479) NOT NULL
  ,quotee VARCHAR(30) NOT NULL
  ,issue  VARCHAR(29) NOT NULL
);
INSERT INTO batman(id,quote,quotee,issue) VALUES (1,'If I have to have a past, then I prefer it to be multiple choice.','Alan Moore','Batman: The Killing Joke');
INSERT INTO batman(id,quote,quotee,issue) VALUES (3,'Adults…struggle desperately with fiction, demanding constantly that it conform to the rules of everyday life. Adults foolishly demand to know how Superman can possibly fly, or howBatman can possibly run a multi-billion-dollar business empire during the day and fight crime at night, when the answer is obvious even to the smallest child: because it’s not real.','Grant Morrison','Supergods');
INSERT INTO batman(id,quote,quotee,issue) VALUES (5,'You don’t get heaven or hell. Do you know the only reward you get for beingBatman? You get to beBatman.','Neil Gaiman','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (7,'Don’t talk like one of them. You’re not! Even if you’d like to be. To them, you’re just a freak, like me! They need you right now, but when they don’t, they’ll cast you out, like a leper! You see, their morals, their code, it’s a bad joke. Dropped at the first sign of trouble. They’re only as good as the world allows them to be. I’ll show you. When the chips are down, these… these civilized people, they’ll eat each other. See, I’m not a monster. I’m just ahead of the curve.','Christoper Nolan as The Joker','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (9,'Ladies. Gentlemen. You have eaten well. You’ve eaten Gotham’s wealth. Its spirit. Your feast is nearly over. From this moment on…none of you are safe.','Frank Miller','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (11,'I’m the goddamnBatman.','Frank Miller','All-StarBatman and Robin');
INSERT INTO batman(id,quote,quotee,issue) VALUES (13,'You either die a hero or you live long enough to see yourself become the villain.','Harvey Dent','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (15,'Batman: a force of chaos in my world of perfect order. The dark side of the Soviet dream. Rumored to be a thousand murdered dissidents, they said he was a ghost. A walking dead man. A symbol of rebellion that would never fade as long as the system survived. Anarchy in black.','Mark Millar','Superman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (17,'Alfred: Hmf. I suppose you’ll take up flying next, like that fellow in Metropolis.','Frank Miller','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (19,'Batman is easily my most favorite character beside Spawn.','Todd McFarlane','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (21,'It’s not who I am underneath, but what I do that defines me.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (23,'Sometimes the truth isn’t good enough, sometimes people need more.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (25,'A hero can be anyone, even a man doing something as simple as reassuring putting a coat on a young boy’s shoulders.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (27,'I have one power. I never give up.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (29,'Why do we fall? So that we can learn to pick ourselves up.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (31,'All men have limits. They learn what they are and learn not to exceed them. I ignore mine','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (33,'Everything’s impossible until somebody does it.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (35,'If you can carry it to the top of the mountain you may find what you were looking for in the first place.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (37,'But I know the rage that drives you. That impossible anger strangling the grief, until the memory of your loved ones is just poison in your veins. And one day you catch yourself wishing the person you loved had never existed, so you’d be spared your pain. ? Christopher Nolan','Ras-al-gul','Batman begins');
INSERT INTO batman(id,quote,quotee,issue) VALUES (39,'Show some respect. They were your grandparents.’ ‘Just names and dusty frames on the wall to me.’ ‘I take exception to that. There is not a speck of dust collecting on those portraits.’','Peter J. Tomasi','Batman and Robin');
INSERT INTO batman(id,quote,quotee,issue) VALUES (41,'Fear clears the mind. Panic clouds it.','Marie Lu','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (43,'[At his parents’ graves] I’ve brought a young man — a boy, actually — to stay at the house. He’s … lost his parents at roughly the same age that I … That I lost you. I don’t know what will happen. I don’t see myself as any sort of father figure. But … I think I can make a difference in his life.','Jeph Loeb','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (45,'Gotham may have lost its king and queen, Bruce, but it could still have its prince','Geoff Johns','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (47,'And yes, it all might end at any moment for any of us, in violence or not, but what matters is what we do before that. The lives we lead.','Scott Snyder','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (49,'Batman’s not a hero. He’s a complicated character. I don’t think I could ever play a real hero — there’s always got to be something a little bit wrong. I think it’s because one of my eyes is smaller than the other one.','Robert Pattinson','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (51,'There are no heroes and there are no villains. There are just opposing points of view. That’s all history is… the viscously long battle between world views. And eventually -Finally- no matter how much it may hurt, Truth wins out. Every. Damn. Time.','Peter J. Tomasi','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (53,'Sometimes people identified too strongly with the famous—it was one of the prices of notoriety, especially when so many considered you to be a hero.Batman sometimes filled much too large a hole in people’s lives.','Craig Shaw Gardner','TheBatman Murders');
INSERT INTO batman(id,quote,quotee,issue) VALUES (55,'Harvey. Grundy. Myself. Each of us lost pieces of our lives……and hid what was left in the dark, is this what I want for myself? A world that exists only in darkness?','Jeph Loeb','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (57,'This is what happens when an unstoppable force meets an immovable object. You truly are incorruptible, aren’t you? You won’t kill me out of some misplaced sense of self-righteousness. And I won’t kill you because you’re just too much fun. I think you and I are destined to do this forever.','The Joker','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (59,'Bats frighten me. It’s time my enemies share my dread.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (61,'Perhaps the knife was too slow.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (63,'Tell me where the trigger is, then you have my permission to die.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (65,'Drive sports cars, date movie stars, buy things that are not for sale… who knows, Master Wayne? You start pretending to have fun, you might even have a little by accident.','Alfred Pennyworth','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (67,'The night is darkest just before the dawn. And I promise you, the dawn is coming.','Harvey Dent','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (69,'People need dramatic examples to shake them out of apathy and I can’t do that as Bruce Wayne. As a man I’m flesh and blood, I can be ignored, I can be destroyed, but as a symbol, as a symbol I can be incorruptible. I can be everlasting.','Bruce Wayne','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (71,'It’s not who I am underneath, but what I do that defines me.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (73,'I’m whatever Gotham needs me to be.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (75,'Because we have to chase him. Because he’s the hero Gotham deserves, but not the one it needs right now, so we’ll hunt him. Because he can take it, because he’s not a hero. He’s a silent guardian, a watchful protector, a Dark Knight.','James Gordon','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (77,'Run, Bruce! Run from the truth! Run like you always have…but when you feel that prickling on the back of your neck, know that I’m coming for you! Reaching you from the other side of your reflection!','Scott Snyder','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (79,'Desire becomes surrender. Surrender becomes Power.','The Joker','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (81,'You’re not a superhero. You’re a spy. With a gun. You’re not Wing-Knight or Nightwing or whatever. You’re agent 37.','Tom King','Grayson');
INSERT INTO batman(id,quote,quotee,issue) VALUES (83,'The Joker as sadistic chaos, theBatman as merciless order. This mirror-image theme would come to define the two characters’ relationship in the comics and across all media for the next forty years.','Glen Weldon','The Caped Crusade');
INSERT INTO batman(id,quote,quotee,issue) VALUES (85,'The whereabouts ofBatman remain unknown. And yet… I can see him now, in the grip of implacable forces, innumerable foes. Somewhere without hope. In a place where all seems lost. And I know this… the enemy will look away, for just a moment, underestimating him for that single fraction of a second too long. And no matter how dark the night… there will be no hiding place for evil.','Grant Morrison','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (87,'Batman was human. He had no powers. He stood next to Gods and said, I handle my city.','Scott Snyder','Batman (2011-2016) #46');
INSERT INTO batman(id,quote,quotee,issue) VALUES (89,'A gun is a coward’s weapon. A liar’s weapon. We kill…too often because we’ve made it easy…too easy…sparing ourselves the mess.. and the work..','Frank Miller','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (91,'We all look for meaning behind the tragedies that befall us. And sometimes the meaning is there. But sometimes, Master Bruce, terrible things just happen. No sinister plots. No secret societies. They just happen.','Batman vs. Robin','Alfred');
INSERT INTO batman(id,quote,quotee,issue) VALUES (93,'Live bravely in the time you have and smile at the void.','Scott Snyder','Batman (2011-2016) #40');
INSERT INTO batman(id,quote,quotee,issue) VALUES (95,'I always claimed I became theBatman to fight crime. That was a lie. I did it to overcome the fear.','Jim Starlin','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (97,'This city just showed you that it’s full of people ready to believe in good.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (99,'You cannot lead these men unless you are prepared to do what is necessary to defeat evil.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (101,'Why do we fall, Bruce? So that we can learn to pick ourselves back up.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (103,'Criminals are like weeds, Alfred; pull one up, another grows in its place.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (105,'I respect the mind’s power over the body. It’s why I do what I do.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (107,'I knew Harvey Dent, I was his friend and it will be a very long time before someone…Inspires us the way he did.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (109,'Gotham, take control… take control of your city. Behold, the instrument of your liberation! Identify yourself to the world!','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (111,'Sometimes people deserve to have their faith rewarded','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (113,'Targeting me won’t get their money back. I knew the mob wouldn’t go down without a fight, but this is different. They crossed the line.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (115,'Gambol: You’re just a freak in a cheap suit. Joker: The suit, it ain’t cheap, you oughta know you bought it.','Gambol/Joker','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (117,'This city just showed you that it’s full of people ready to believe in good.','Batman/Bruce Wayne','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (119,'Some men aren’t looking for anything logical like money. They can’t be bought, bullied, reasoned or negotiated with.','Alfred Pennyworth','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (121,'You thought we could be decent men in an indecent time! But you were wrong. The world is cruel.','Two-Face','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (123,'It is a far, far better thing that I do than I have ever done; it is a far, far better rest that I go to than I have ever known.','Jim Gordon','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (125,'The first time I stole so that I wouldn’t starve, I lost many assumptions about the simple nature of right and wrong. And when I traveled, I learned the fear before a crime and the thrill of success. But I never became one of them.','Bruce Wayne','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (127,'A criminal is not complicated. What you really fear is inside yourself. You fear your own power. You fear your anger, the drive to do great or terrible things.','Ra’s Al Ghul','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (129,'Justice is balance. You burned my house and left me for dead. Consider us even.','Ra’s Al Ghul','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (131,'Bruce…if you turn yourself in, they’re not gonna let us be together.','Rachel Dawes','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (133,'You care about justice? Look beyond your own pain, Bruce. This city is rotting. People talk about the depression as if it’s history. It’s not. Things are worse than ever down here.','Rachel Dawes','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (135,'Always be yourself! Unless you can beBatman, then always beBatman.','Shadowtext','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (137,'Any negative trait, if known, becomes your ultimate trait. Unless you areBatman.','Nikhil Sharda','Sans Destination');
INSERT INTO batman(id,quote,quotee,issue) VALUES (139,'Say, what’s the question mark for? Sexual identity?','Dan Slott','Arkham Asylum');
INSERT INTO batman(id,quote,quotee,issue) VALUES (141,'The antidote to joy is dread.','Sam Hamm','Batman: Blind Justice');
INSERT INTO batman(id,quote,quotee,issue) VALUES (143,'DoesBatman ever NOT have a plan…?','Mark Waid','Kingdom Come #2');
INSERT INTO batman(id,quote,quotee,issue) VALUES (145,'We must not remind them that giants walk the Earth.','Frank Miller','Batman');
INSERT INTO batman(id,quote,quotee,issue) VALUES (147,'Gotham City. Clean shafts of concrete and snowy rooftops. The work of men who died generations ago. From here, it looks like an achievement. From here, you can’t see the enemy.','Frank Miller','Batman: Year One');
INSERT INTO batman(id,quote,quotee,issue) VALUES (149,'I made a promise to my parents that I would rid the city of the evil that took their lives.','Jeph Loeb','Batman: The Long Halloween');
INSERT INTO batman(id,quote,quotee,issue) VALUES (151,'I’m thinking of killing everyone whose name is a palindrome','Dan Slott','Arkham Asylum');
INSERT INTO batman(id,quote,quotee,issue) VALUES (153,'Lots of folks would argue that Bruce hides behind his perfectly coiffed hair and ever-easy smile far more thanBatman does underneath his cowl.','Paul Asay','God on the Streets of Gotham');
INSERT INTO batman(id,quote,quotee,issue) VALUES (155,'People need dramatic examples to shake them out of apathy.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (157,'Sometimes it’s only madness that makes us what we are.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (159,'I wear a mask. And that mask, it’s not to hide who I am, but to create what I am.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (161,'If I have to have a past, then I prefer it to be multiple choice.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (163,'Without warning, it comes…crashing through the window of your study, and mine…I have seen it before…somewhere. It frightened me as a boy… frightened me. Yes, father. I shall become a bat.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (165,'I won’t kill you, but I don’t I have to save you.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (167,'If you need to stop an asteroid, you call Superman. If you need to solve a mystery, you callBatman. But if you need to end a war, you call Wonder Woman.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (169,'You finally learned to do what is necessary.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (171,'You are as precious to me as you were to your own mother and father. I swore to them that I would protect you, and I haven’t.','Batman','Not Found');
INSERT INTO batman(id,quote,quotee,issue) VALUES (173,'It’s obvious. Only a criminal would disguise himself as a licensed, bonded guard yet callously park in front of a fire hydrant.','Batman','Not Found');
